spring.datasource.url=jdbc:mysql://localhost:3306/cinema_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=Duchuy0367683356
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

booking.seat-hold-duration-minutes=5
booking.seat-hold-cleanup-milliseconds=10000

payment.vietqr.bank-id=${VIETQR_BANK_ID:970422}
payment.vietqr.bank-name=${VIETQR_BANK_NAME:MB Bank}
payment.vietqr.account-number=${VIETQR_ACCOUNT_NUMBER:0889329886}
payment.vietqr.account-name=${VIETQR_ACCOUNT_NAME:NGUYEN HA HAI DANG}
payment.vietqr.template=${VIETQR_TEMPLATE:compact2}
payment.vietqr.image-base-url=https://img.vietqr.io/imagegit status

payment.vnpay.tmn-code=${VNPAY_TMN_CODE:}
payment.vnpay.hash-secret=${VNPAY_HASH_SECRET:}

payment.vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.query-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

payment.vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:8080/api/payments/vnpay/return}
payment.vnpay.frontend-result-url=${VNPAY_FRONTEND_RESULT_URL:http://localhost:5173/payment/vnpay-return}

payment.vnpay.version=2.1.0
payment.vnpay.command=pay
payment.vnpay.currency-code=VND
payment.vnpay.locale=vn
payment.vnpay.order-type=other



