SET NAMES utf8mb4;

INSERT INTO genres (id, name) VALUES
(1, 'Hành động'),
(2, 'Phiêu lưu'),
(3, 'Hoạt hình'),
(4, 'Hài'),
(5, 'Tâm lý'),
(6, 'Giả tưởng'),
(7, 'Kinh dị'),
(8, 'Tình cảm'),
(9, 'Khoa học viễn tưởng'),
(10, 'Giật gân'),
(11, 'Gia đình'),
(12, 'Bí ẩn');

INSERT INTO movies (
  id,
  title,
  description,
  duration_minutes,
  release_date,
  age_rating,
  director,
  cast,
  language,
  poster_url,
  trailer_url,
  status,
  created_at,
  updated_at
) VALUES
(1, 'Dune: Hành Tinh Cát - Phần Hai', 'Paul Atreides liên minh với Chani và người Fremen để trả thù những kẻ đã hủy hoại gia tộc mình, đồng thời đối mặt lựa chọn có thể thay đổi vận mệnh thiên hà.', 166, '2024-03-01', 'T13', 'Denis Villeneuve', 'Timothee Chalamet, Zendaya, Rebecca Ferguson', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 'https://www.youtube.com/watch?v=Way9Dexny3w', 'SHOWING', '2026-09-01 08:00:00', '2026-09-01 08:00:00'),
(2, 'Những Mảnh Ghép Cảm Xúc 2', 'Riley bước vào tuổi thiếu niên, kéo theo sự xuất hiện của nhiều cảm xúc mới khiến tổng hành dinh trở nên hỗn loạn và đáng yêu hơn bao giờ hết.', 96, '2024-06-14', 'P', 'Kelsey Mann', 'Amy Poehler, Maya Hawke, Kensington Tallman', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', 'https://www.youtube.com/watch?v=LEjhY15eCx0', 'SHOWING', '2026-09-01 08:05:00', '2026-09-01 08:05:00'),
(3, 'Godzilla x Kong: Đế Chế Mới', 'Godzilla và Kong phải đối đầu một hiểm họa khổng lồ đang trỗi dậy từ sâu trong Trái Đất Rỗng, đe dọa sự tồn vong của cả hai giống loài.', 115, '2024-03-29', 'T13', 'Adam Wingard', 'Rebecca Hall, Brian Tyree Henry, Dan Stevens', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg', 'https://www.youtube.com/watch?v=lV1OOlGwExM', 'SHOWING', '2026-09-01 08:10:00', '2026-09-01 08:10:00'),
(4, 'Furiosa: Câu Chuyện Từ Max Điên', 'Bị bắt khỏi quê hương khi còn nhỏ, Furiosa phải sống sót giữa vùng đất hoang tàn và tìm đường trở về nơi mình thuộc về.', 149, '2024-05-24', 'T16', 'George Miller', 'Anya Taylor-Joy, Chris Hemsworth, Tom Burke', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg', 'https://www.youtube.com/watch?v=XJMuhwVlca4', 'UPCOMING', '2026-09-01 08:15:00', '2026-09-01 08:15:00'),
(5, 'Vùng Đất Câm Lặng: Ngày Một', 'Một người phụ nữ phải tìm cách sống sót trong những giờ đầu tiên của cuộc xâm lăng bí ẩn, khi âm thanh trở thành mối nguy chết người.', 99, '2024-06-28', 'T16', 'Michael Sarnoski', 'Lupita Nyongo, Joseph Quinn, Alex Wolff', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/hU42CRk14JuPEdqZG3AWmagiPAP.jpg', 'https://www.youtube.com/watch?v=YPY7J-flzE8', 'UPCOMING', '2026-09-01 08:20:00', '2026-09-01 08:20:00'),
(6, 'Mai', 'Mai, một người phụ nữ từng trải qua nhiều tổn thương, bất ngờ gặp một tình yêu mới nhưng cũng phải đối diện với những vết thương cũ chưa lành.', 131, '2024-02-10', 'T18', 'Trấn Thành', 'Phương Anh Đào, Tuấn Trần, Trấn Thành', 'Tiếng Việt', 'https://cdn-i.doisongphapluat.com.vn/media/trieu-phuong-linh/2024/01/17/dao-dien-tran-thanh-xay-dung-vu-tru-spa-va-vu-tru-hang-xom-day-mau-sac-trong-phim-mai1.jpg', 'https://www.youtube.com/watch?v=example-mai', 'SHOWING', '2026-09-01 08:25:00', '2026-09-01 08:25:00'),
(7, 'Lật Mặt 7: Một Điều Ước', 'Câu chuyện gia đình cảm động về tình thân, sự hy sinh và mong ước được đưa những người thân yêu trở lại gần nhau.', 138, '2024-04-26', 'P', 'Lý Hải', 'Thanh Hiền, Trương Minh Cường, Đinh Y Nhung', 'Tiếng Việt', 'https://i.imgur.com/VP8sUZ5.jpg', 'https://www.youtube.com/watch?v=example-lat-mat-7', 'SHOWING', '2026-09-01 08:30:00', '2026-09-01 08:30:00'),
(8, 'Kung Fu Panda 4', 'Po chuẩn bị trở thành thủ lĩnh tinh thần của Thung lũng Bình Yên và phải huấn luyện một chiến binh mới trước hiểm họa đang đến gần.', 94, '2024-03-08', 'P', 'Mike Mitchell', 'Jack Black, Awkwafina, Viola Davis', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg', 'https://www.youtube.com/watch?v=_inKs4eeHiI', 'ENDED', '2026-09-01 08:35:00', '2026-09-01 08:35:00'),
(9, 'Kẻ Thế Thân', 'Một diễn viên đóng thế bị cuốn vào vụ mất tích bí ẩn trong khi cố hàn gắn mối quan hệ với người yêu cũ.', 126, '2024-05-03', 'T13', 'David Leitch', 'Ryan Gosling, Emily Blunt, Aaron Taylor-Johnson', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/tSz1qsmSJon0rqjHBxXZmrotuse.jpg', 'https://www.youtube.com/watch?v=j7jPnwVGdZ8', 'ENDED', '2026-09-01 08:40:00', '2026-09-01 08:40:00'),
(10, 'Kẻ Trộm Mặt Trăng 4', 'Gru và gia đình phải thích nghi với thành viên mới trong nhà, đồng thời đối mặt một kẻ thù nguy hiểm vừa xuất hiện.', 95, '2024-07-03', 'P', 'Chris Renaud', 'Steve Carell, Kristen Wiig, Will Ferrell', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/wWba3TaojhK7NdycRhoQpsG0FaH.jpg', 'https://www.youtube.com/watch?v=qQlr9-rF32A', 'UPCOMING', '2026-09-01 08:45:00', '2026-09-01 08:45:00'),
(11, 'Deadpool & Wolverine', 'Deadpool hợp tác cùng Wolverine trong một nhiệm vụ náo loạn xuyên dòng thời gian, kéo theo hàng loạt rắc rối khó lường.', 128, '2024-07-26', 'T18', 'Shawn Levy', 'Ryan Reynolds, Hugh Jackman, Emma Corrin', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg', 'https://www.youtube.com/watch?v=73_1biulkYk', 'UPCOMING', '2026-09-01 08:50:00', '2026-09-01 08:50:00'),
(12, 'Thám Tử Lừng Danh Conan: Ngôi Sao 5 Cánh 1 Triệu Đô', 'Conan điều tra vụ án xoay quanh một thanh kiếm, kho báu bí mật và tên trộm nguy hiểm tại Hakodate.', 111, '2024-04-12', 'T13', 'Chika Nagaoka', 'Minami Takayama, Wakana Yamazaki, Rikiya Koyama', 'Tiếng Nhật', 'https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg', 'https://www.youtube.com/watch?v=example-conan', 'SHOWING', '2026-09-01 08:55:00', '2026-09-01 08:55:00'),
(13, 'Quật Mộ Trùng Ma', 'Một nhóm pháp sư và chuyên gia phong thủy khai quật ngôi mộ cổ, từ đó đánh thức bí mật đen tối ám ảnh cả một gia tộc.', 134, '2024-02-22', 'T16', 'Jang Jae-hyun', 'Choi Min-sik, Kim Go-eun, Yoo Hae-jin', 'Tiếng Hàn', 'https://image.tmdb.org/t/p/w500/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg', 'https://www.youtube.com/watch?v=example-exhuma', 'ENDED', '2026-09-01 09:00:00', '2026-09-01 09:00:00'),
(14, 'Lốc Xoáy Tử Thần', 'Một thế hệ thợ săn bão mới liều mình tiến vào tâm lốc xoáy để nghiên cứu và ngăn chặn thảm họa thiên nhiên.', 122, '2024-07-19', 'T13', 'Lee Isaac Chung', 'Daisy Edgar-Jones, Glen Powell, Anthony Ramos', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg', 'https://www.youtube.com/watch?v=wdok0rZdmx4', 'UPCOMING', '2026-09-01 09:05:00', '2026-09-01 09:05:00'),
(15, 'Mưa Đỏ', 'Một người lính trẻ Việt Nam cùng đồng đội trải qua mất mát, lòng trung thành và lòng dũng cảm giữa thời chiến.', 124, '2026-04-30', 'T16', 'Nguyễn Quang Dũng', 'Quốc Huy, B Trần, Huyền Lizzie', 'Tiếng Việt', 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', 'https://www.youtube.com/watch?v=example-mua-do', 'INACTIVE', '2026-09-01 09:10:00', '2026-09-01 09:10:00'),
(16, 'Robot Hoang Dã', 'Một robot bị mắc kẹt trên đảo hoang phải học cách thích nghi, chăm sóc và trở thành một phần của thế giới tự nhiên.', 102, '2024-09-27', 'P', 'Chris Sanders', 'Lupita Nyongo, Pedro Pascal, Kit Connor', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg', 'https://www.youtube.com/watch?v=67vbA5ZJdKQ', 'UPCOMING', '2026-09-01 09:15:00', '2026-09-01 09:15:00'),
(17, 'Alien: Romulus', 'Một nhóm thực dân trẻ trong không gian chạm trán sinh vật ngoài hành tinh đáng sợ trên một trạm vũ trụ bỏ hoang.', 119, '2024-08-16', 'T18', 'Fede Alvarez', 'Cailee Spaeny, David Jonsson, Archie Renaux', 'Tiếng Anh', 'https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg', 'https://www.youtube.com/watch?v=x0XDEhP4MQs', 'UPCOMING', '2026-09-01 09:20:00', '2026-09-01 09:20:00'),
(18, 'Thành Phố Ngủ Quên', 'Một người thợ chiếu phim tỉnh lẻ lên Thành phố Hồ Chí Minh để cứu rạp chiếu cuối cùng của gia đình mình.', 108, '2026-08-21', 'T13', 'Lê Minh Hoàng', 'Khả Ngân, Song Luân, Hồng Ánh', 'Tiếng Việt', 'https://image.tmdb.org/t/p/w500/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg', 'https://www.youtube.com/watch?v=example-thanh-pho', 'SHOWING', '2026-09-01 09:25:00', '2026-09-01 09:25:00');

INSERT INTO movie_genres (movie_id, genre_id) VALUES
(1, 1),
(1, 2),
(1, 5),
(1, 9),
(2, 2),
(2, 3),
(2, 4),
(2, 11),
(3, 1),
(3, 2),
(3, 9),
(4, 1),
(4, 2),
(4, 10),
(5, 7),
(5, 9),
(5, 10),
(6, 5),
(6, 8),
(7, 4),
(7, 5),
(7, 11),
(8, 1),
(8, 2),
(8, 3),
(8, 4),
(9, 1),
(9, 4),
(9, 8),
(10, 3),
(10, 4),
(10, 11),
(11, 1),
(11, 4),
(11, 9),
(12, 2),
(12, 3),
(12, 12),
(13, 7),
(13, 10),
(13, 12),
(14, 1),
(14, 2),
(14, 10),
(15, 1),
(15, 5),
(16, 2),
(16, 3),
(16, 5),
(16, 11),
(17, 7),
(17, 9),
(17, 10),
(18, 5),
(18, 8);

INSERT INTO cinema_rooms (id, name, room_type, total_seats, status) VALUES
(1, 'Phòng 01', '2D', 120, 'ACTIVE'),
(2, 'Phòng 02', '2D', 100, 'ACTIVE'),
(3, 'Phòng IMAX 03', 'IMAX', 180, 'ACTIVE'),
(4, 'Phòng VIP 04', 'VIP', 72, 'ACTIVE'),
(5, 'Phòng 4DX 05', '4DX', 96, 'MAINTENANCE');

INSERT INTO showtimes (id, movie_id, room_id, start_time, end_time, status, created_at) VALUES
(1, 1, 3, '2026-09-08 09:00:00', '2026-09-08 11:46:00', 'OPEN', '2026-09-01 10:00:00'),
(2, 1, 3, '2026-09-08 19:30:00', '2026-09-08 22:16:00', 'OPEN', '2026-09-01 10:00:00'),
(3, 2, 1, '2026-09-08 10:15:00', '2026-09-08 11:51:00', 'OPEN', '2026-09-01 10:00:00'),
(4, 3, 2, '2026-09-08 13:30:00', '2026-09-08 15:25:00', 'OPEN', '2026-09-01 10:00:00'),
(5, 6, 4, '2026-09-08 20:00:00', '2026-09-08 22:11:00', 'OPEN', '2026-09-01 10:00:00'),
(6, 7, 1, '2026-09-09 09:30:00', '2026-09-09 11:48:00', 'OPEN', '2026-09-01 10:00:00'),
(7, 11, 3, '2026-09-09 18:45:00', '2026-09-09 20:53:00', 'OPEN', '2026-09-01 10:00:00'),
(8, 12, 2, '2026-09-10 14:00:00', '2026-09-10 15:51:00', 'OPEN', '2026-09-01 10:00:00'),
(9, 16, 1, '2026-09-10 16:30:00', '2026-09-10 18:12:00', 'OPEN', '2026-09-01 10:00:00'),
(10, 17, 4, '2026-09-10 21:15:00', '2026-09-10 23:14:00', 'OPEN', '2026-09-01 10:00:00'),
(11, 18, 2, '2026-09-11 18:00:00', '2026-09-11 19:48:00', 'OPEN', '2026-09-01 10:00:00'),
(12, 4, 5, '2026-09-12 20:20:00', '2026-09-12 22:49:00', 'CLOSED', '2026-09-01 10:00:00');

INSERT INTO seats (room_id, row_label, seat_number, seat_type, status) VALUES
(1, 'A', 1, 'NORMAL', 'ACTIVE'),
(1, 'A', 2, 'NORMAL', 'ACTIVE'),
(1, 'A', 3, 'NORMAL', 'ACTIVE'),
(1, 'A', 4, 'NORMAL', 'ACTIVE'),
(1, 'A', 5, 'NORMAL', 'ACTIVE'),
(1, 'A', 6, 'NORMAL', 'ACTIVE'),
(1, 'A', 7, 'NORMAL', 'ACTIVE'),
(1, 'A', 8, 'NORMAL', 'ACTIVE'),
(1, 'A', 9, 'NORMAL', 'ACTIVE'),
(1, 'A', 10, 'NORMAL', 'ACTIVE'),
(1, 'B', 1, 'NORMAL', 'ACTIVE'),
(1, 'B', 2, 'NORMAL', 'ACTIVE'),
(1, 'B', 3, 'NORMAL', 'ACTIVE'),
(1, 'B', 4, 'NORMAL', 'ACTIVE'),
(1, 'B', 5, 'NORMAL', 'ACTIVE'),
(1, 'B', 6, 'NORMAL', 'ACTIVE'),
(1, 'B', 7, 'NORMAL', 'ACTIVE'),
(1, 'B', 8, 'NORMAL', 'ACTIVE'),
(1, 'B', 9, 'NORMAL', 'ACTIVE'),
(1, 'B', 10, 'NORMAL', 'ACTIVE'),
(1, 'C', 1, 'VIP', 'ACTIVE'),
(1, 'C', 2, 'VIP', 'ACTIVE'),
(1, 'C', 3, 'NORMAL', 'ACTIVE'),
(1, 'C', 4, 'NORMAL', 'ACTIVE'),
(1, 'C', 5, 'NORMAL', 'ACTIVE'),
(1, 'C', 6, 'NORMAL', 'ACTIVE'),
(1, 'C', 7, 'NORMAL', 'ACTIVE'),
(1, 'C', 8, 'NORMAL', 'ACTIVE'),
(1, 'C', 9, 'NORMAL', 'ACTIVE'),
(1, 'C', 10, 'NORMAL', 'ACTIVE'),
(1, 'D', 1, 'VIP', 'ACTIVE'),
(1, 'D', 2, 'VIP', 'ACTIVE'),
(1, 'D', 3, 'NORMAL', 'ACTIVE'),
(1, 'D', 4, 'NORMAL', 'ACTIVE'),
(1, 'D', 5, 'NORMAL', 'ACTIVE'),
(1, 'D', 6, 'NORMAL', 'ACTIVE'),
(1, 'D', 7, 'NORMAL', 'ACTIVE'),
(1, 'D', 8, 'NORMAL', 'ACTIVE'),
(1, 'D', 9, 'NORMAL', 'ACTIVE'),
(1, 'D', 10, 'NORMAL', 'ACTIVE'),
(1, 'E', 1, 'VIP', 'ACTIVE'),
(1, 'E', 2, 'VIP', 'ACTIVE'),
(1, 'E', 3, 'NORMAL', 'ACTIVE'),
(1, 'E', 4, 'NORMAL', 'ACTIVE'),
(1, 'E', 5, 'NORMAL', 'ACTIVE'),
(1, 'E', 6, 'NORMAL', 'ACTIVE'),
(1, 'E', 7, 'NORMAL', 'ACTIVE'),
(1, 'E', 8, 'NORMAL', 'ACTIVE'),
(1, 'E', 9, 'NORMAL', 'ACTIVE'),
(1, 'E', 10, 'NORMAL', 'ACTIVE'),
(1, 'F', 1, 'VIP', 'ACTIVE'),
(1, 'F', 2, 'VIP', 'ACTIVE'),
(1, 'F', 3, 'NORMAL', 'ACTIVE'),
(1, 'F', 4, 'NORMAL', 'ACTIVE'),
(1, 'F', 5, 'NORMAL', 'ACTIVE'),
(1, 'F', 6, 'NORMAL', 'ACTIVE'),
(1, 'F', 7, 'NORMAL', 'ACTIVE'),
(1, 'F', 8, 'NORMAL', 'ACTIVE'),
(1, 'F', 9, 'NORMAL', 'ACTIVE'),
(1, 'F', 10, 'NORMAL', 'ACTIVE'),
(1, 'G', 1, 'VIP', 'ACTIVE'),
(1, 'G', 2, 'VIP', 'ACTIVE'),
(1, 'G', 3, 'NORMAL', 'ACTIVE'),
(1, 'G', 4, 'NORMAL', 'ACTIVE'),
(1, 'G', 5, 'NORMAL', 'ACTIVE'),
(1, 'G', 6, 'NORMAL', 'ACTIVE'),
(1, 'G', 7, 'NORMAL', 'ACTIVE'),
(1, 'G', 8, 'NORMAL', 'ACTIVE'),
(1, 'G', 9, 'NORMAL', 'ACTIVE'),
(1, 'G', 10, 'NORMAL', 'ACTIVE'),
(1, 'H', 1, 'VIP', 'ACTIVE'),
(1, 'H', 2, 'VIP', 'ACTIVE'),
(1, 'H', 3, 'NORMAL', 'ACTIVE'),
(1, 'H', 4, 'NORMAL', 'ACTIVE'),
(1, 'H', 5, 'NORMAL', 'ACTIVE'),
(1, 'H', 6, 'NORMAL', 'ACTIVE'),
(1, 'H', 7, 'NORMAL', 'ACTIVE'),
(1, 'H', 8, 'NORMAL', 'ACTIVE'),
(1, 'H', 9, 'NORMAL', 'ACTIVE'),
(1, 'H', 10, 'NORMAL', 'ACTIVE'),
(1, 'I', 1, 'VIP', 'ACTIVE'),
(1, 'I', 2, 'VIP', 'ACTIVE'),
(1, 'I', 3, 'NORMAL', 'ACTIVE'),
(1, 'I', 4, 'NORMAL', 'ACTIVE'),
(1, 'I', 5, 'NORMAL', 'ACTIVE'),
(1, 'I', 6, 'NORMAL', 'ACTIVE'),
(1, 'I', 7, 'NORMAL', 'ACTIVE'),
(1, 'I', 8, 'NORMAL', 'ACTIVE'),
(1, 'I', 9, 'NORMAL', 'ACTIVE'),
(1, 'I', 10, 'NORMAL', 'ACTIVE'),
(1, 'J', 1, 'VIP', 'ACTIVE'),
(1, 'J', 2, 'VIP', 'ACTIVE'),
(1, 'J', 3, 'NORMAL', 'ACTIVE'),
(1, 'J', 4, 'NORMAL', 'ACTIVE'),
(1, 'J', 5, 'NORMAL', 'ACTIVE'),
(1, 'J', 6, 'NORMAL', 'ACTIVE'),
(1, 'J', 7, 'NORMAL', 'ACTIVE'),
(1, 'J', 8, 'NORMAL', 'ACTIVE'),
(1, 'J', 9, 'NORMAL', 'ACTIVE'),
(1, 'J', 10, 'NORMAL', 'ACTIVE'),
(1, 'K', 1, 'VIP', 'ACTIVE'),
(1, 'K', 2, 'VIP', 'ACTIVE'),
(1, 'K', 3, 'NORMAL', 'ACTIVE'),
(1, 'K', 4, 'NORMAL', 'ACTIVE'),
(1, 'K', 5, 'NORMAL', 'ACTIVE'),
(1, 'K', 6, 'NORMAL', 'ACTIVE'),
(1, 'K', 7, 'NORMAL', 'ACTIVE'),
(1, 'K', 8, 'NORMAL', 'ACTIVE'),
(1, 'K', 9, 'NORMAL', 'ACTIVE'),
(1, 'K', 10, 'NORMAL', 'ACTIVE'),
(1, 'L', 1, 'VIP', 'ACTIVE'),
(1, 'L', 2, 'VIP', 'ACTIVE'),
(1, 'L', 3, 'NORMAL', 'ACTIVE'),
(1, 'L', 4, 'NORMAL', 'ACTIVE'),
(1, 'L', 5, 'NORMAL', 'ACTIVE'),
(1, 'L', 6, 'NORMAL', 'ACTIVE'),
(1, 'L', 7, 'NORMAL', 'ACTIVE'),
(1, 'L', 8, 'NORMAL', 'ACTIVE'),
(1, 'L', 9, 'NORMAL', 'ACTIVE'),
(1, 'L', 10, 'NORMAL', 'ACTIVE'),
(2, 'A', 1, 'NORMAL', 'ACTIVE'),
(2, 'A', 2, 'NORMAL', 'ACTIVE'),
(2, 'A', 3, 'NORMAL', 'ACTIVE'),
(2, 'A', 4, 'NORMAL', 'ACTIVE'),
(2, 'A', 5, 'NORMAL', 'ACTIVE'),
(2, 'A', 6, 'NORMAL', 'ACTIVE'),
(2, 'A', 7, 'NORMAL', 'ACTIVE'),
(2, 'A', 8, 'NORMAL', 'ACTIVE'),
(2, 'A', 9, 'NORMAL', 'ACTIVE'),
(2, 'A', 10, 'NORMAL', 'ACTIVE'),
(2, 'B', 1, 'NORMAL', 'ACTIVE'),
(2, 'B', 2, 'NORMAL', 'ACTIVE'),
(2, 'B', 3, 'NORMAL', 'ACTIVE'),
(2, 'B', 4, 'NORMAL', 'ACTIVE'),
(2, 'B', 5, 'NORMAL', 'ACTIVE'),
(2, 'B', 6, 'NORMAL', 'ACTIVE'),
(2, 'B', 7, 'NORMAL', 'ACTIVE'),
(2, 'B', 8, 'NORMAL', 'ACTIVE'),
(2, 'B', 9, 'NORMAL', 'ACTIVE'),
(2, 'B', 10, 'NORMAL', 'ACTIVE'),
(2, 'C', 1, 'VIP', 'ACTIVE'),
(2, 'C', 2, 'VIP', 'ACTIVE'),
(2, 'C', 3, 'NORMAL', 'ACTIVE'),
(2, 'C', 4, 'NORMAL', 'ACTIVE'),
(2, 'C', 5, 'NORMAL', 'ACTIVE'),
(2, 'C', 6, 'NORMAL', 'ACTIVE'),
(2, 'C', 7, 'NORMAL', 'ACTIVE'),
(2, 'C', 8, 'NORMAL', 'ACTIVE'),
(2, 'C', 9, 'NORMAL', 'ACTIVE'),
(2, 'C', 10, 'NORMAL', 'ACTIVE'),
(2, 'D', 1, 'VIP', 'ACTIVE'),
(2, 'D', 2, 'VIP', 'ACTIVE'),
(2, 'D', 3, 'NORMAL', 'ACTIVE'),
(2, 'D', 4, 'NORMAL', 'ACTIVE'),
(2, 'D', 5, 'NORMAL', 'ACTIVE'),
(2, 'D', 6, 'NORMAL', 'ACTIVE'),
(2, 'D', 7, 'NORMAL', 'ACTIVE'),
(2, 'D', 8, 'NORMAL', 'ACTIVE'),
(2, 'D', 9, 'NORMAL', 'ACTIVE'),
(2, 'D', 10, 'NORMAL', 'ACTIVE'),
(2, 'E', 1, 'VIP', 'ACTIVE'),
(2, 'E', 2, 'VIP', 'ACTIVE'),
(2, 'E', 3, 'NORMAL', 'ACTIVE'),
(2, 'E', 4, 'NORMAL', 'ACTIVE'),
(2, 'E', 5, 'NORMAL', 'ACTIVE'),
(2, 'E', 6, 'NORMAL', 'ACTIVE'),
(2, 'E', 7, 'NORMAL', 'ACTIVE'),
(2, 'E', 8, 'NORMAL', 'ACTIVE'),
(2, 'E', 9, 'NORMAL', 'ACTIVE'),
(2, 'E', 10, 'NORMAL', 'ACTIVE'),
(2, 'F', 1, 'VIP', 'ACTIVE'),
(2, 'F', 2, 'VIP', 'ACTIVE'),
(2, 'F', 3, 'NORMAL', 'ACTIVE'),
(2, 'F', 4, 'NORMAL', 'ACTIVE'),
(2, 'F', 5, 'NORMAL', 'ACTIVE'),
(2, 'F', 6, 'NORMAL', 'ACTIVE'),
(2, 'F', 7, 'NORMAL', 'ACTIVE'),
(2, 'F', 8, 'NORMAL', 'ACTIVE'),
(2, 'F', 9, 'NORMAL', 'ACTIVE'),
(2, 'F', 10, 'NORMAL', 'ACTIVE'),
(2, 'G', 1, 'VIP', 'ACTIVE'),
(2, 'G', 2, 'VIP', 'ACTIVE'),
(2, 'G', 3, 'NORMAL', 'ACTIVE'),
(2, 'G', 4, 'NORMAL', 'ACTIVE'),
(2, 'G', 5, 'NORMAL', 'ACTIVE'),
(2, 'G', 6, 'NORMAL', 'ACTIVE'),
(2, 'G', 7, 'NORMAL', 'ACTIVE'),
(2, 'G', 8, 'NORMAL', 'ACTIVE'),
(2, 'G', 9, 'NORMAL', 'ACTIVE'),
(2, 'G', 10, 'NORMAL', 'ACTIVE'),
(2, 'H', 1, 'VIP', 'ACTIVE'),
(2, 'H', 2, 'VIP', 'ACTIVE'),
(2, 'H', 3, 'NORMAL', 'ACTIVE'),
(2, 'H', 4, 'NORMAL', 'ACTIVE'),
(2, 'H', 5, 'NORMAL', 'ACTIVE'),
(2, 'H', 6, 'NORMAL', 'ACTIVE'),
(2, 'H', 7, 'NORMAL', 'ACTIVE'),
(2, 'H', 8, 'NORMAL', 'ACTIVE'),
(2, 'H', 9, 'NORMAL', 'ACTIVE'),
(2, 'H', 10, 'NORMAL', 'ACTIVE'),
(2, 'I', 1, 'VIP', 'ACTIVE'),
(2, 'I', 2, 'VIP', 'ACTIVE'),
(2, 'I', 3, 'NORMAL', 'ACTIVE'),
(2, 'I', 4, 'NORMAL', 'ACTIVE'),
(2, 'I', 5, 'NORMAL', 'ACTIVE'),
(2, 'I', 6, 'NORMAL', 'ACTIVE'),
(2, 'I', 7, 'NORMAL', 'ACTIVE'),
(2, 'I', 8, 'NORMAL', 'ACTIVE'),
(2, 'I', 9, 'NORMAL', 'ACTIVE'),
(2, 'I', 10, 'NORMAL', 'ACTIVE'),
(2, 'J', 1, 'VIP', 'ACTIVE'),
(2, 'J', 2, 'VIP', 'ACTIVE'),
(2, 'J', 3, 'NORMAL', 'ACTIVE'),
(2, 'J', 4, 'NORMAL', 'ACTIVE'),
(2, 'J', 5, 'NORMAL', 'ACTIVE'),
(2, 'J', 6, 'NORMAL', 'ACTIVE'),
(2, 'J', 7, 'NORMAL', 'ACTIVE'),
(2, 'J', 8, 'NORMAL', 'ACTIVE'),
(2, 'J', 9, 'NORMAL', 'ACTIVE'),
(2, 'J', 10, 'NORMAL', 'ACTIVE'),
(3, 'A', 1, 'NORMAL', 'ACTIVE'),
(3, 'A', 2, 'NORMAL', 'ACTIVE'),
(3, 'A', 3, 'NORMAL', 'ACTIVE'),
(3, 'A', 4, 'NORMAL', 'ACTIVE'),
(3, 'A', 5, 'NORMAL', 'ACTIVE'),
(3, 'A', 6, 'NORMAL', 'ACTIVE'),
(3, 'A', 7, 'NORMAL', 'ACTIVE'),
(3, 'A', 8, 'NORMAL', 'ACTIVE'),
(3, 'A', 9, 'NORMAL', 'ACTIVE'),
(3, 'A', 10, 'NORMAL', 'ACTIVE'),
(3, 'B', 1, 'NORMAL', 'ACTIVE'),
(3, 'B', 2, 'NORMAL', 'ACTIVE'),
(3, 'B', 3, 'NORMAL', 'ACTIVE'),
(3, 'B', 4, 'NORMAL', 'ACTIVE'),
(3, 'B', 5, 'NORMAL', 'ACTIVE'),
(3, 'B', 6, 'NORMAL', 'ACTIVE'),
(3, 'B', 7, 'NORMAL', 'ACTIVE'),
(3, 'B', 8, 'NORMAL', 'ACTIVE'),
(3, 'B', 9, 'NORMAL', 'ACTIVE'),
(3, 'B', 10, 'NORMAL', 'ACTIVE'),
(3, 'C', 1, 'VIP', 'ACTIVE'),
(3, 'C', 2, 'VIP', 'ACTIVE'),
(3, 'C', 3, 'NORMAL', 'ACTIVE'),
(3, 'C', 4, 'NORMAL', 'ACTIVE'),
(3, 'C', 5, 'NORMAL', 'ACTIVE'),
(3, 'C', 6, 'NORMAL', 'ACTIVE'),
(3, 'C', 7, 'NORMAL', 'ACTIVE'),
(3, 'C', 8, 'NORMAL', 'ACTIVE'),
(3, 'C', 9, 'NORMAL', 'ACTIVE'),
(3, 'C', 10, 'NORMAL', 'ACTIVE'),
(3, 'D', 1, 'VIP', 'ACTIVE'),
(3, 'D', 2, 'VIP', 'ACTIVE'),
(3, 'D', 3, 'NORMAL', 'ACTIVE'),
(3, 'D', 4, 'NORMAL', 'ACTIVE'),
(3, 'D', 5, 'NORMAL', 'ACTIVE'),
(3, 'D', 6, 'NORMAL', 'ACTIVE'),
(3, 'D', 7, 'NORMAL', 'ACTIVE'),
(3, 'D', 8, 'NORMAL', 'ACTIVE'),
(3, 'D', 9, 'NORMAL', 'ACTIVE'),
(3, 'D', 10, 'NORMAL', 'ACTIVE'),
(3, 'E', 1, 'VIP', 'ACTIVE'),
(3, 'E', 2, 'VIP', 'ACTIVE'),
(3, 'E', 3, 'NORMAL', 'ACTIVE'),
(3, 'E', 4, 'NORMAL', 'ACTIVE'),
(3, 'E', 5, 'NORMAL', 'ACTIVE'),
(3, 'E', 6, 'NORMAL', 'ACTIVE'),
(3, 'E', 7, 'NORMAL', 'ACTIVE'),
(3, 'E', 8, 'NORMAL', 'ACTIVE'),
(3, 'E', 9, 'NORMAL', 'ACTIVE'),
(3, 'E', 10, 'NORMAL', 'ACTIVE'),
(3, 'F', 1, 'VIP', 'ACTIVE'),
(3, 'F', 2, 'VIP', 'ACTIVE'),
(3, 'F', 3, 'NORMAL', 'ACTIVE'),
(3, 'F', 4, 'NORMAL', 'ACTIVE'),
(3, 'F', 5, 'NORMAL', 'ACTIVE'),
(3, 'F', 6, 'NORMAL', 'ACTIVE'),
(3, 'F', 7, 'NORMAL', 'ACTIVE'),
(3, 'F', 8, 'NORMAL', 'ACTIVE'),
(3, 'F', 9, 'NORMAL', 'ACTIVE'),
(3, 'F', 10, 'NORMAL', 'ACTIVE'),
(3, 'G', 1, 'VIP', 'ACTIVE'),
(3, 'G', 2, 'VIP', 'ACTIVE'),
(3, 'G', 3, 'NORMAL', 'ACTIVE'),
(3, 'G', 4, 'NORMAL', 'ACTIVE'),
(3, 'G', 5, 'NORMAL', 'ACTIVE'),
(3, 'G', 6, 'NORMAL', 'ACTIVE'),
(3, 'G', 7, 'NORMAL', 'ACTIVE'),
(3, 'G', 8, 'NORMAL', 'ACTIVE'),
(3, 'G', 9, 'NORMAL', 'ACTIVE'),
(3, 'G', 10, 'NORMAL', 'ACTIVE'),
(3, 'H', 1, 'VIP', 'ACTIVE'),
(3, 'H', 2, 'VIP', 'ACTIVE'),
(3, 'H', 3, 'NORMAL', 'ACTIVE'),
(3, 'H', 4, 'NORMAL', 'ACTIVE'),
(3, 'H', 5, 'NORMAL', 'ACTIVE'),
(3, 'H', 6, 'NORMAL', 'ACTIVE'),
(3, 'H', 7, 'NORMAL', 'ACTIVE'),
(3, 'H', 8, 'NORMAL', 'ACTIVE'),
(3, 'H', 9, 'NORMAL', 'ACTIVE'),
(3, 'H', 10, 'NORMAL', 'ACTIVE'),
(3, 'I', 1, 'VIP', 'ACTIVE'),
(3, 'I', 2, 'VIP', 'ACTIVE'),
(3, 'I', 3, 'NORMAL', 'ACTIVE'),
(3, 'I', 4, 'NORMAL', 'ACTIVE'),
(3, 'I', 5, 'NORMAL', 'ACTIVE'),
(3, 'I', 6, 'NORMAL', 'ACTIVE'),
(3, 'I', 7, 'NORMAL', 'ACTIVE'),
(3, 'I', 8, 'NORMAL', 'ACTIVE'),
(3, 'I', 9, 'NORMAL', 'ACTIVE'),
(3, 'I', 10, 'NORMAL', 'ACTIVE'),
(3, 'J', 1, 'VIP', 'ACTIVE'),
(3, 'J', 2, 'VIP', 'ACTIVE'),
(3, 'J', 3, 'NORMAL', 'ACTIVE'),
(3, 'J', 4, 'NORMAL', 'ACTIVE'),
(3, 'J', 5, 'NORMAL', 'ACTIVE'),
(3, 'J', 6, 'NORMAL', 'ACTIVE'),
(3, 'J', 7, 'NORMAL', 'ACTIVE'),
(3, 'J', 8, 'NORMAL', 'ACTIVE'),
(3, 'J', 9, 'NORMAL', 'ACTIVE'),
(3, 'J', 10, 'NORMAL', 'ACTIVE'),
(3, 'K', 1, 'VIP', 'ACTIVE'),
(3, 'K', 2, 'VIP', 'ACTIVE'),
(3, 'K', 3, 'NORMAL', 'ACTIVE'),
(3, 'K', 4, 'NORMAL', 'ACTIVE'),
(3, 'K', 5, 'NORMAL', 'ACTIVE'),
(3, 'K', 6, 'NORMAL', 'ACTIVE'),
(3, 'K', 7, 'NORMAL', 'ACTIVE'),
(3, 'K', 8, 'NORMAL', 'ACTIVE'),
(3, 'K', 9, 'NORMAL', 'ACTIVE'),
(3, 'K', 10, 'NORMAL', 'ACTIVE'),
(3, 'L', 1, 'VIP', 'ACTIVE'),
(3, 'L', 2, 'VIP', 'ACTIVE'),
(3, 'L', 3, 'NORMAL', 'ACTIVE'),
(3, 'L', 4, 'NORMAL', 'ACTIVE'),
(3, 'L', 5, 'NORMAL', 'ACTIVE'),
(3, 'L', 6, 'NORMAL', 'ACTIVE'),
(3, 'L', 7, 'NORMAL', 'ACTIVE'),
(3, 'L', 8, 'NORMAL', 'ACTIVE'),
(3, 'L', 9, 'NORMAL', 'ACTIVE'),
(3, 'L', 10, 'NORMAL', 'ACTIVE'),
(3, 'M', 1, 'VIP', 'ACTIVE'),
(3, 'M', 2, 'VIP', 'ACTIVE'),
(3, 'M', 3, 'NORMAL', 'ACTIVE'),
(3, 'M', 4, 'NORMAL', 'ACTIVE'),
(3, 'M', 5, 'NORMAL', 'ACTIVE'),
(3, 'M', 6, 'NORMAL', 'ACTIVE'),
(3, 'M', 7, 'NORMAL', 'ACTIVE'),
(3, 'M', 8, 'NORMAL', 'ACTIVE'),
(3, 'M', 9, 'NORMAL', 'ACTIVE'),
(3, 'M', 10, 'NORMAL', 'ACTIVE'),
(3, 'N', 1, 'VIP', 'ACTIVE'),
(3, 'N', 2, 'VIP', 'ACTIVE'),
(3, 'N', 3, 'NORMAL', 'ACTIVE'),
(3, 'N', 4, 'NORMAL', 'ACTIVE'),
(3, 'N', 5, 'NORMAL', 'ACTIVE'),
(3, 'N', 6, 'NORMAL', 'ACTIVE'),
(3, 'N', 7, 'NORMAL', 'ACTIVE'),
(3, 'N', 8, 'NORMAL', 'ACTIVE'),
(3, 'N', 9, 'NORMAL', 'ACTIVE'),
(3, 'N', 10, 'NORMAL', 'ACTIVE'),
(3, 'O', 1, 'VIP', 'ACTIVE'),
(3, 'O', 2, 'VIP', 'ACTIVE'),
(3, 'O', 3, 'NORMAL', 'ACTIVE'),
(3, 'O', 4, 'NORMAL', 'ACTIVE'),
(3, 'O', 5, 'NORMAL', 'ACTIVE'),
(3, 'O', 6, 'NORMAL', 'ACTIVE'),
(3, 'O', 7, 'NORMAL', 'ACTIVE'),
(3, 'O', 8, 'NORMAL', 'ACTIVE'),
(3, 'O', 9, 'NORMAL', 'ACTIVE'),
(3, 'O', 10, 'NORMAL', 'ACTIVE'),
(3, 'P', 1, 'VIP', 'ACTIVE'),
(3, 'P', 2, 'VIP', 'ACTIVE'),
(3, 'P', 3, 'NORMAL', 'ACTIVE'),
(3, 'P', 4, 'NORMAL', 'ACTIVE'),
(3, 'P', 5, 'NORMAL', 'ACTIVE'),
(3, 'P', 6, 'NORMAL', 'ACTIVE'),
(3, 'P', 7, 'NORMAL', 'ACTIVE'),
(3, 'P', 8, 'NORMAL', 'ACTIVE'),
(3, 'P', 9, 'NORMAL', 'ACTIVE'),
(3, 'P', 10, 'NORMAL', 'ACTIVE'),
(3, 'Q', 1, 'VIP', 'ACTIVE'),
(3, 'Q', 2, 'VIP', 'ACTIVE'),
(3, 'Q', 3, 'NORMAL', 'ACTIVE'),
(3, 'Q', 4, 'NORMAL', 'ACTIVE'),
(3, 'Q', 5, 'NORMAL', 'ACTIVE'),
(3, 'Q', 6, 'NORMAL', 'ACTIVE'),
(3, 'Q', 7, 'NORMAL', 'ACTIVE'),
(3, 'Q', 8, 'NORMAL', 'ACTIVE'),
(3, 'Q', 9, 'NORMAL', 'ACTIVE'),
(3, 'Q', 10, 'NORMAL', 'ACTIVE'),
(3, 'R', 1, 'VIP', 'ACTIVE'),
(3, 'R', 2, 'VIP', 'ACTIVE'),
(3, 'R', 3, 'NORMAL', 'ACTIVE'),
(3, 'R', 4, 'NORMAL', 'ACTIVE'),
(3, 'R', 5, 'NORMAL', 'ACTIVE'),
(3, 'R', 6, 'NORMAL', 'ACTIVE'),
(3, 'R', 7, 'NORMAL', 'ACTIVE'),
(3, 'R', 8, 'NORMAL', 'ACTIVE'),
(3, 'R', 9, 'NORMAL', 'ACTIVE'),
(3, 'R', 10, 'NORMAL', 'ACTIVE'),
(4, 'A', 1, 'NORMAL', 'ACTIVE'),
(4, 'A', 2, 'NORMAL', 'ACTIVE'),
(4, 'A', 3, 'NORMAL', 'ACTIVE'),
(4, 'A', 4, 'NORMAL', 'ACTIVE'),
(4, 'A', 5, 'NORMAL', 'ACTIVE'),
(4, 'A', 6, 'NORMAL', 'ACTIVE'),
(4, 'A', 7, 'NORMAL', 'ACTIVE'),
(4, 'A', 8, 'NORMAL', 'ACTIVE'),
(4, 'A', 9, 'NORMAL', 'ACTIVE'),
(4, 'A', 10, 'NORMAL', 'ACTIVE'),
(4, 'B', 1, 'NORMAL', 'ACTIVE'),
(4, 'B', 2, 'NORMAL', 'ACTIVE'),
(4, 'B', 3, 'NORMAL', 'ACTIVE'),
(4, 'B', 4, 'NORMAL', 'ACTIVE'),
(4, 'B', 5, 'NORMAL', 'ACTIVE'),
(4, 'B', 6, 'NORMAL', 'ACTIVE'),
(4, 'B', 7, 'NORMAL', 'ACTIVE'),
(4, 'B', 8, 'NORMAL', 'ACTIVE'),
(4, 'B', 9, 'NORMAL', 'ACTIVE'),
(4, 'B', 10, 'NORMAL', 'ACTIVE'),
(4, 'C', 1, 'VIP', 'ACTIVE'),
(4, 'C', 2, 'VIP', 'ACTIVE'),
(4, 'C', 3, 'NORMAL', 'ACTIVE'),
(4, 'C', 4, 'NORMAL', 'ACTIVE'),
(4, 'C', 5, 'NORMAL', 'ACTIVE'),
(4, 'C', 6, 'NORMAL', 'ACTIVE'),
(4, 'C', 7, 'NORMAL', 'ACTIVE'),
(4, 'C', 8, 'NORMAL', 'ACTIVE'),
(4, 'C', 9, 'NORMAL', 'ACTIVE'),
(4, 'C', 10, 'NORMAL', 'ACTIVE'),
(4, 'D', 1, 'VIP', 'ACTIVE'),
(4, 'D', 2, 'VIP', 'ACTIVE'),
(4, 'D', 3, 'NORMAL', 'ACTIVE'),
(4, 'D', 4, 'NORMAL', 'ACTIVE'),
(4, 'D', 5, 'NORMAL', 'ACTIVE'),
(4, 'D', 6, 'NORMAL', 'ACTIVE'),
(4, 'D', 7, 'NORMAL', 'ACTIVE'),
(4, 'D', 8, 'NORMAL', 'ACTIVE'),
(4, 'D', 9, 'NORMAL', 'ACTIVE'),
(4, 'D', 10, 'NORMAL', 'ACTIVE'),
(4, 'E', 1, 'VIP', 'ACTIVE'),
(4, 'E', 2, 'VIP', 'ACTIVE'),
(4, 'E', 3, 'NORMAL', 'ACTIVE'),
(4, 'E', 4, 'NORMAL', 'ACTIVE'),
(4, 'E', 5, 'NORMAL', 'ACTIVE'),
(4, 'E', 6, 'NORMAL', 'ACTIVE'),
(4, 'E', 7, 'NORMAL', 'ACTIVE'),
(4, 'E', 8, 'NORMAL', 'ACTIVE'),
(4, 'E', 9, 'NORMAL', 'ACTIVE'),
(4, 'E', 10, 'NORMAL', 'ACTIVE'),
(4, 'F', 1, 'VIP', 'ACTIVE'),
(4, 'F', 2, 'VIP', 'ACTIVE'),
(4, 'F', 3, 'NORMAL', 'ACTIVE'),
(4, 'F', 4, 'NORMAL', 'ACTIVE'),
(4, 'F', 5, 'NORMAL', 'ACTIVE'),
(4, 'F', 6, 'NORMAL', 'ACTIVE'),
(4, 'F', 7, 'NORMAL', 'ACTIVE'),
(4, 'F', 8, 'NORMAL', 'ACTIVE'),
(4, 'F', 9, 'NORMAL', 'ACTIVE'),
(4, 'F', 10, 'NORMAL', 'ACTIVE'),
(4, 'G', 1, 'VIP', 'ACTIVE'),
(4, 'G', 2, 'VIP', 'ACTIVE'),
(4, 'G', 3, 'NORMAL', 'ACTIVE'),
(4, 'G', 4, 'NORMAL', 'ACTIVE'),
(4, 'G', 5, 'NORMAL', 'ACTIVE'),
(4, 'G', 6, 'NORMAL', 'ACTIVE'),
(4, 'G', 7, 'NORMAL', 'ACTIVE'),
(4, 'G', 8, 'NORMAL', 'ACTIVE'),
(4, 'G', 9, 'NORMAL', 'ACTIVE'),
(4, 'G', 10, 'NORMAL', 'ACTIVE'),
(4, 'H', 1, 'VIP', 'ACTIVE'),
(4, 'H', 2, 'VIP', 'ACTIVE'),
(5, 'A', 1, 'NORMAL', 'INACTIVE'),
(5, 'A', 2, 'NORMAL', 'INACTIVE'),
(5, 'A', 3, 'NORMAL', 'INACTIVE'),
(5, 'A', 4, 'NORMAL', 'INACTIVE'),
(5, 'A', 5, 'NORMAL', 'INACTIVE'),
(5, 'A', 6, 'NORMAL', 'INACTIVE'),
(5, 'A', 7, 'NORMAL', 'ACTIVE'),
(5, 'A', 8, 'NORMAL', 'ACTIVE'),
(5, 'A', 9, 'NORMAL', 'ACTIVE'),
(5, 'A', 10, 'NORMAL', 'ACTIVE'),
(5, 'B', 1, 'NORMAL', 'ACTIVE'),
(5, 'B', 2, 'NORMAL', 'ACTIVE'),
(5, 'B', 3, 'NORMAL', 'ACTIVE'),
(5, 'B', 4, 'NORMAL', 'ACTIVE'),
(5, 'B', 5, 'NORMAL', 'ACTIVE'),
(5, 'B', 6, 'NORMAL', 'ACTIVE'),
(5, 'B', 7, 'NORMAL', 'ACTIVE'),
(5, 'B', 8, 'NORMAL', 'ACTIVE'),
(5, 'B', 9, 'NORMAL', 'ACTIVE'),
(5, 'B', 10, 'NORMAL', 'ACTIVE'),
(5, 'C', 1, 'VIP', 'ACTIVE'),
(5, 'C', 2, 'VIP', 'ACTIVE'),
(5, 'C', 3, 'NORMAL', 'ACTIVE'),
(5, 'C', 4, 'NORMAL', 'ACTIVE'),
(5, 'C', 5, 'NORMAL', 'ACTIVE'),
(5, 'C', 6, 'NORMAL', 'ACTIVE'),
(5, 'C', 7, 'NORMAL', 'ACTIVE'),
(5, 'C', 8, 'NORMAL', 'ACTIVE'),
(5, 'C', 9, 'NORMAL', 'ACTIVE'),
(5, 'C', 10, 'NORMAL', 'ACTIVE'),
(5, 'D', 1, 'VIP', 'ACTIVE'),
(5, 'D', 2, 'VIP', 'ACTIVE'),
(5, 'D', 3, 'NORMAL', 'ACTIVE'),
(5, 'D', 4, 'NORMAL', 'ACTIVE'),
(5, 'D', 5, 'NORMAL', 'ACTIVE'),
(5, 'D', 6, 'NORMAL', 'ACTIVE'),
(5, 'D', 7, 'NORMAL', 'ACTIVE'),
(5, 'D', 8, 'NORMAL', 'ACTIVE'),
(5, 'D', 9, 'NORMAL', 'ACTIVE'),
(5, 'D', 10, 'NORMAL', 'ACTIVE'),
(5, 'E', 1, 'VIP', 'ACTIVE'),
(5, 'E', 2, 'VIP', 'ACTIVE'),
(5, 'E', 3, 'NORMAL', 'ACTIVE'),
(5, 'E', 4, 'NORMAL', 'ACTIVE'),
(5, 'E', 5, 'NORMAL', 'ACTIVE'),
(5, 'E', 6, 'NORMAL', 'ACTIVE'),
(5, 'E', 7, 'NORMAL', 'ACTIVE'),
(5, 'E', 8, 'NORMAL', 'ACTIVE'),
(5, 'E', 9, 'NORMAL', 'ACTIVE'),
(5, 'E', 10, 'NORMAL', 'ACTIVE'),
(5, 'F', 1, 'VIP', 'ACTIVE'),
(5, 'F', 2, 'VIP', 'ACTIVE'),
(5, 'F', 3, 'NORMAL', 'ACTIVE'),
(5, 'F', 4, 'NORMAL', 'ACTIVE'),
(5, 'F', 5, 'NORMAL', 'ACTIVE'),
(5, 'F', 6, 'NORMAL', 'ACTIVE'),
(5, 'F', 7, 'NORMAL', 'ACTIVE'),
(5, 'F', 8, 'NORMAL', 'ACTIVE'),
(5, 'F', 9, 'NORMAL', 'ACTIVE'),
(5, 'F', 10, 'NORMAL', 'ACTIVE'),
(5, 'G', 1, 'VIP', 'ACTIVE'),
(5, 'G', 2, 'VIP', 'ACTIVE'),
(5, 'G', 3, 'NORMAL', 'ACTIVE'),
(5, 'G', 4, 'NORMAL', 'ACTIVE'),
(5, 'G', 5, 'NORMAL', 'ACTIVE'),
(5, 'G', 6, 'NORMAL', 'ACTIVE'),
(5, 'G', 7, 'NORMAL', 'ACTIVE'),
(5, 'G', 8, 'NORMAL', 'ACTIVE'),
(5, 'G', 9, 'NORMAL', 'ACTIVE'),
(5, 'G', 10, 'NORMAL', 'ACTIVE'),
(5, 'H', 1, 'VIP', 'ACTIVE'),
(5, 'H', 2, 'VIP', 'ACTIVE'),
(5, 'H', 3, 'NORMAL', 'ACTIVE'),
(5, 'H', 4, 'NORMAL', 'ACTIVE'),
(5, 'H', 5, 'NORMAL', 'ACTIVE'),
(5, 'H', 6, 'NORMAL', 'ACTIVE'),
(5, 'H', 7, 'NORMAL', 'ACTIVE'),
(5, 'H', 8, 'NORMAL', 'ACTIVE'),
(5, 'H', 9, 'NORMAL', 'ACTIVE'),
(5, 'H', 10, 'NORMAL', 'ACTIVE'),
(5, 'I', 1, 'VIP', 'ACTIVE'),
(5, 'I', 2, 'VIP', 'ACTIVE'),
(5, 'I', 3, 'NORMAL', 'ACTIVE'),
(5, 'I', 4, 'NORMAL', 'ACTIVE'),
(5, 'I', 5, 'NORMAL', 'ACTIVE'),
(5, 'I', 6, 'NORMAL', 'ACTIVE'),
(5, 'I', 7, 'NORMAL', 'ACTIVE'),
(5, 'I', 8, 'NORMAL', 'ACTIVE'),
(5, 'I', 9, 'NORMAL', 'ACTIVE'),
(5, 'I', 10, 'NORMAL', 'ACTIVE'),
(5, 'J', 1, 'VIP', 'ACTIVE'),
(5, 'J', 2, 'VIP', 'ACTIVE'),
(5, 'J', 3, 'NORMAL', 'ACTIVE'),
(5, 'J', 4, 'NORMAL', 'ACTIVE'),
(5, 'J', 5, 'NORMAL', 'ACTIVE'),
(5, 'J', 6, 'NORMAL', 'ACTIVE');

